Name: nemo-qml-plugin-systemsettings
Summary: System settings plugin for Nemo Mobile
URL: https://github.com/nemomobile/nemo-qml-plugin-systemsettings
Group: System/Libraries
Description: "%{summary}."
Version: 0.0.0
Release: 1
Sources:
    - "%{name}-%{version}.tar.bz2"
License: BSD
Configure: none
Builder: qmake5
PkgConfigBR:
    - Qt5Qml
    - Qt5SystemInfo
    - qmsystem2-qt5
    - profile
    - mce
Files:
    - "%{_libdir}/qt5/qml/org/nemomobile/systemsettings/libnemosystemsettings.so"
    - "%{_libdir}/qt5/qml/org/nemomobile/systemsettings/qmldir"
    - "%{_libdir}/libsystemsettings.so.*"

SubPackages:
    - Name: devel
      Summary: System settings C++ library
      Group: System/Libraries
      Description: "%{summary}."
      Files:
          - "%{_libdir}/pkgconfig/systemsettings.pc"
          - "%{_includedir}/systemsettings/*"
          - "%{_libdir}/libsystemsettings.so"
